#
# Module manifest for module 'LoginDemo' that is not actually ready to use.
#
# Generated by: Katie Kodes
#
# Generated on: 4/21/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'LoginDemo.psm1'

    # Source code lists ModuleVersion as "0.0.0" as a stand-in.  Use the "Version" option when we run Build-Module with a real version number.
    ModuleVersion = '0.0.0'

    # ID used to uniquely identify this module
    GUID = '25bde448-d34b-4340-bb17-1fdd4246ce0a'

    # Author of this module
    Author            = 'Katie Kodes'

    # Company or vendor of this module
    CompanyName       = 'Katie Kodes'

    # Copyright statement for this module
    Copyright         = '(c) 2026 Katie Kodes. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'GitHub app CLI login demonstration'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '7.0'

    # This module only includes functions, so only "FunctionsToExport" is included.
    FunctionsToExport = '*'
}